// Auto-generated by odin-protoc-plugin (https://github.com/lordhippo/odin-protoc-plugin)
// protoc version: 3.21.12
// Use with the runtime odin-protobuf library (https://github.com/lordhippo/odin-protobuf)

package proto_example

Dog :: struct {
  name : string `id:"1" type:"9"`,
  colour : string `id:"2" type:"9"`,
}
