// Auto-generated by odin-protoc-plugin (https://github.com/lordhippo/odin-protoc-plugin)
// protoc version: 3.21.12
// Use with the runtime odin-protobuf library (https://github.com/lordhippo/odin-protobuf)

package proto_example

House :: struct {
  rooms : i32 `id:"1" type:"5"`,
}
